{
  'variables': {
    # Configure for armv7 compilation
    'target_arch': 'arm64',
    'OS' : 'linux',
    'chromeos' : 0,
    'embedded' : 0,
    'desktop_linux' : 1,
    'os_posix' : 1,
    'linux_use_bundled_binutils' :  0,
    'linux_use_debug_fission' : 0,
    'disable_glibc' : 0,
    'extra_warnings' : 0,
    'enable_mpeg2ts_stream_parser' : 1,
    'use_v4lplugin' : 1,
    'build_ffmpegsumo' : 1,
    'ffmpeg_branding' : 'Chrome',
    'v8_target_arch' : 'arm64',
    'v8_use_arm_eabi_hardfloat' : 1,
    'use_system_libxml' : 1,
    'use_system_libxslt' : 1,
    'use_system_libevent' : 1,
    'use_system_libvpx' : 1,
    'use_system_libusb' : 1,
    'use_system_libpng' : 1,
    'use_system_jsoncpp' : 1,
    'use_system_flac' : 1,
    'use_system_fontconfig' : 1,
    'use_system_openssl' : 1,
    'use_system_speex' : 1,
    'use_alsa' : 1,
    'use_system_icu' : 0,
    'use_glib' : 1,
    'nacl_untrusted_build': 1,
    'use_aura' : 1,
    'use_xkbcommon' : 1,
    'remove_webcore_debug_symbols' : 1,
    'use_gconf' : 0,
    'use_ozone' : 1,
    'ozone_auto_platforms' : 0,
    'ozone_platform' : 'wayland',
    'ozone_platform_wayland' : 1,
    'enable_plugins' : 1,
    'disable_fatal_linker_warnings' : 1,
    'use_allocator': 0,
  },
}
